{{ with .Values.deployment -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .label }}
    spec:
      containers:
        - name: {{ .name }}
          image: {{ .image }}:{{ .version }}
          command:
{{- toYaml .command | nindent 12 }}
{{- end }}