apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-receiver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-receiver
  template:
    metadata:
      labels:
        app: kafka-receiver
    spec:
      containers:
        - name: kafka-receiver
          image: confluentinc/cp-kafkacat:7.1.16
          command:
            - sh
            - -c
            - kafkacat -b whirly-cluster-kafka-bootstrap.kafka:9092 -t grzegorz-topic -C
