apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grzegorz-kafka-app
  namespace: argocd
spec:
  project: grzegorz
  source:
    repoURL: https://github.com/grzegorz-demidziuk/kafkaChart.git
    targetRevision: main
    path: "./kafka-message-app"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: playground
  syncPolicy: 
    automated: {}
 